- name: Create Mysql Backup User
  mysql_user:
    name: "{{ backup_service_user }}"
    host: localhost
    password: "{{ backup_service_user_password }}"
    priv: "*.*:SELECT,RELOAD,LOCK\ TABLES,SHOW\ VIEW,PROCESS"
    state: present
  tags:
    - install-cms-mysql
    - cms-mysql-backup


- name: Set Up Mysql Backup Cron Job
  cron:
    name: "mysql-backup"
    minute: "0"
    hour: "3"
    user: "root"
    job: "{{ backup_cron_job_name }}"
  tags:
    - install-cms-mysql
    - cms-mysql-backup


- name: Ensure Backup Directory Exists and With Correct Permission
  file:
    path: "{{ backup_dir }}"
    owner: "root"
    group: "root"
    mode: 0700
    state: "directory"
  tags:
    - install-cms-mysql
    - cms-mysql-backup
