- name: Set Up MySQL Backup Cron Job
  cron:
    name: "mysql-backup"
    minute: "0"
    hour: "3"
    user: "root"
    job: "{{ backup_cron_job_name }}"
  tags:
    - install-cms-mysql
    - set-cms-mysql-backup


- name: Ensure Backup Directory Exists and With Correct Permission
  file:
    path: "{{ backup_dir }}"
    owner: "root"
    group: "root"
    mode: 0700
    state: "directory"
  tags:
    - install-cms-mysql
    - set-cms-mysql-backup


- name: Create CMS Backup User
  mysql_user:
    name: "{{ cms_backup_user }}"
    host: localhost
    password: "{{ cms_backup_user_password }}"
    priv: "*.*:SELECT,RELOAD,PROCESS,LOCK\ TABLES,SHOW\ VIEW"
    state: present
  tags:
    - install-cms-mysql
    - set-cms-mysql-backup
