- name: Ensure Include Directory Exists and With Correct Permission
  file:
    path: "{{ include_dir }}"
    owner: "root"
    group: "root"
    mode: 0755
    state: "directory"
  tags:
    - install
    - config


- name: Ensure Log_bin Directory Exists and With Correct Permission
  file:
    path: "{{ log_bin_dir }}"
    owner: "{{ mysql_group }}"
    group: "{{ mysql_gid }}"
    mode: 0755
    state: "directory"
  tags:
    - install-mysql
    - config-mysql


- name: Confing Mysql Master
  template:
    src: master.my.cnf.j2
    dest: /etc/my.cnf
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  when: mysql_master_ip_address is defined and mysql_master_ip_address in ansible_all_ipv4_addresses
  tags:
    - install-mysql
    - config-mysql


- name: Confing Mysql Slave
  template:
    src: slave.my.cnf.j2
    dest: /etc/my.cnf
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  when: mysql_slave_ip_address is defined and mysql_slave_ip_address in ansible_all_ipv4_addresses
  tags:
    - install-mysql
    - config-mysql
