- name: Enable Mysql on Boot
  service:
    name: mysqld
    enabled: yes
  become: true
  tags:
    - install-mysql
    - service


- name: Restart Mysql Service
  service:
    name: mysqld
    state: restarted
  become: true
  tags:
    - install-mysql
    - service
